import { resolve } from "path";
import { existsSync } from "fs";
import { readFile, writeFile } from "fs/promises";
import { FlagsConfig, FlagMap } from "./types";
import { printAsTs } from "./ts-printer";

const readConfig = async (): Promise<FlagsConfig> => {
  try {
    const flags = await readFile("flags.json", { encoding: "utf-8" });
    const config = JSON.parse(flags);
    if (config.mergePath === undefined || config.flags === undefined) {
      throw new Error(
        "Invalid flags.json format, expected mergePath and flags as root keys"
      );
    }

    Object.keys(config.flags).forEach((flag) => {
      if (typeof config.flags[flag]?.value !== "boolean") {
        throw new Error(`Flag ${flag} does not have default value set`);
      }
    });

    return config;
  } catch (e) {
    console.error("Error reading flags.json");
    console.error(e);
    process.exit(1);
  }
};

const parseArgs = (args: string[]) => {
  let command;
  const flagsToDisable = new Set<string>();
  const flagsToEnable = new Set<string>();
  args.slice(2).forEach((arg) => {
    if (arg.startsWith("-")) {
      flagsToDisable.add(arg.replace("-", ""));
      return;
    }

    if (arg.startsWith("+")) {
      flagsToEnable.add(arg.replace("+", ""));
      return;
    }

    command = arg;
  });
  return { command, flagsToDisable, flagsToEnable };
};

class BuildFlags {
  flags: FlagMap;

  constructor(defaultFlags: FlagMap) {
    this.flags = defaultFlags;
  }

  enable(enables: Set<string>) {
    enables.forEach((enable) => {
      if (!this.flags[enable]) {
        throw new Error(`Flag ${enable} does not exist, could not enable`);
      }
      this.flags[enable].value = true;
    });
  }

  disable(disables: Set<string>) {
    disables.forEach((disable) => {
      if (!this.flags[disable]) {
        throw new Error(`Flag ${disable} does not exist, could not disable`);
      }
      this.flags[disable].value = false;
    });
  }

  async save(path: string) {
    if (path.endsWith(".json")) {
      const flags = JSON.stringify(this.flags, null, 2);
      await writeFile(resolve(path), flags);
      return;
    }

    if (path.endsWith(".ts")) {
      const ts = printAsTs(this.flags);
      await writeFile(resolve(path), ts);
      return;
    }

    throw new Error(
      "Invalid file extension in flags file for mergePath: expected .json or .ts"
    );
  }
}

const printHelp = (command?: string) => {
  if (command) {
    console.error(`Unknown command: ${command}`);
  }
  console.log(`Usage: build-flags [command] [flags]
  Commands:
    override  Override default flags with provided flag arguments: +flag to enable, -flag to disable
  `);
};

const initFlagsFile = async () => {
  const srcPaths = ["src", "app"];
  const srcFolder = srcPaths.find((path) => existsSync(path));
  const gitignoreExists = existsSync(".gitignore");
  const baseFlags = {
    mergePath: srcFolder ? `${srcFolder}/buildFlags.ts` : "buildFlags.ts",
    flags: {
      exampleFlag: {
        value: false,
        meta: {
          note: "This is an example flag, you can delete this or make it yours!",
        },
      },
    },
  };
  console.log("");
  await writeFile("flags.json", JSON.stringify(baseFlags, null, 2));
  console.log("Wrote default flags to flags.json in the current directory");
  const flags = new BuildFlags(baseFlags.flags);
  await flags.save(baseFlags.mergePath);
  if (gitignoreExists) {
    const gitignore = await readFile(".gitignore", { encoding: "utf-8" });
    await writeFile(
      ".gitignore",
      `${gitignore}\n\n# Runtime build flags generated by npx build-flags\n${baseFlags.mergePath}`
    );
  }
  console.log(
    `Wrote runtime flags to ${baseFlags.mergePath}${
      gitignoreExists ? " (and added this to your .gitignore)" : ""
    }`
  );
};

const run = async () => {
  const { command, flagsToDisable, flagsToEnable } = parseArgs(process.argv);

  if (command === "init") {
    await initFlagsFile();
    return;
  }

  if (command === "override") {
    const { mergePath, flags: defaultFlags } = await readConfig();
    const flags = new BuildFlags(defaultFlags);
    flags.enable(flagsToEnable);
    flags.disable(flagsToDisable);
    await flags.save(mergePath);
    return;
  }

  printHelp(command);
};

run().catch((e) => {
  console.error(e);
  process.exit(1);
});
